### ISSUE TITLE
Filter menu not visible on hd mobile screen iphone6

### ISSUE THREAD

**Issue by josefkreitmayer** [TransforMap/transformap-viewer#39] opened 2016-10-01 15:54 UTC
As I tested the icons on the Iphone6 of my sister, I noticed that the filter menu does not show.

I assume, that is due to the resolution of 1334x750.

**Comment by species** [comment] 2016-10-02 08:48
Your assumption is correct, it switches to the mobile layout below 768px width.

Is the "show filters"-button visible and does it work? Then its not a bug, but a feature and this issue can be closed.

**Comment by josef-legacy-account** [comment] 2016-10-02 16:55
No, on the iphone 6 it is just a turquoise screen, that does not go anywhere. I think the map shows initially, then when you click on the filter menu, turquoise screen.

**Comment by species** [comment] 2016-10-02 17:07
Could you give a detailed step-by-step-instruction how to reproduce this bug?
- which of the 3 forks did you visit, and when?
- Which Browser was used, does it show on every Browser?
- Where did you click (or tap)
- what happens if you visit the site in landscape mode (it should be wider than 768px then)
- if you see something not as simple as a 100% turquoise screen, please attach a screenshot.

**Comment by josefkreitmayer** [comment] 2016-10-02 18:53
I will ask my sister to check different options.

The only click was on the filter icon on the map, then the turquoise screen appeared without any possibility to go back.

**Comment by josefkreitmayer** [comment] 2016-10-02 18:54
can I ask you for the Links of the 3 forks.

I am just familiar with the viewer.transformap.co and the icon one. It was one of those. I suppose the viewer.transformap.co, as I typed it.

**Comment by species** [comment] 2016-10-05 21:08
The three links can be found on the bottom of the README.md in every repo. - Just scroll down, if you visit a Github repo.

**Comment by josef-legacy-account** [comment] 2016-10-11 11:40
The screen is just turquoise, and the filter button to the left is visible. Once pressing the button, it simply disappears, and the screen remains turquoise.

**Comment by josef-legacy-account** [comment] 2016-10-27 11:44
@fthprojects tested the link on her mobile device (iphone SE) and it doesn't seem to work. Attach a screenshot with the page appeared after typing the url. Could you please check it?

![14872410_10211608377467627_1215675772_n](https://cloud.githubusercontent.com/assets/23098277/19765758/cd0cb7e2-9c52-11e6-8768-d07299566653.jpg)

**Comment by josef-legacy-account** [comment] 2016-10-27 11:50
@fthprojects we are aware of the issue, and will process it once the editor is running. Currently it is marked as postponed. 

Thank you for your patience. Even if we cannot solve the issue right away, please keep on reporting anything you find not working as expected or think would be a good enhancement.

**Comment by species** [comment] 2016-11-09 17:47
Please test if this was fixed together with #46 .

**Comment by josef-legacy-account** [comment] 2016-11-09 20:19
@fthprojects, could you test again, the issue should be resoved by now, and the map be running on the iphone6
 https://susy-partners.github.io/transformap-viewer/#3/42.03/13.89

**Comment by fthprojects** [comment] 2016-11-10 10:28
@josefkreitmayer @species yes the problem is resolved. The map is running on iphone 6.

**Closed as completed** 2016-11-10 11:39 UTC
Labels: bug, postponed
